# Generated by Django 3.0.5 on 2020-05-11 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200510_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, related_name='solicitantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
