# Generated by Django 3.0.5 on 2020-05-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_user_isopened'),
        ('usuarios', '0007_user_following'),
    ]

    operations = [
    ]
