# Generated by Django 3.0.5 on 2020-05-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_merge_20200513_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
