# Generated by Django 3.0.5 on 2020-05-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pius', '0003_auto_20200511_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=140),
        ),
    ]
